<a href="https://colab.research.google.com/github/Kalyani-Moram/Netflix-data-recommendations/blob/main/Capstone_project_Netflix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

** Capstone Project - Netflix  -- 06.05.2025

**OBJECTIVE**

1. Find out the list of most popular and liked genre

2. Create Model that finds the best suited Movie for one
  user in every genre

3.Find what Genre Movies have received the best and
  worst ratings based on User Rating.

**Data set Info:**

1.ID Contains the separate keys for customer and movies.

2.Rating A section contains the user ratings for all the movies.

3.Genre Highlights the category of the movie.

4.Movie Name Name of the movie with respect to the movie id.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## To read the data

In [ ]:
df = pd.read_csv('/content/combinedNetflixData.txt',header=None,usecols=[0,1],names=['CustID','Ratings'])

df

           CustID  Ratings
0              1:      NaN
1         1488844      3.0
2          822109      5.0
3          885013      4.0
4           30878      4.0
...           ...      ...
24058258  2591364      2.0
24058259  1791000      2.0
24058260   512536      5.0
24058261   988963      3.0
24058262  1704416      3.0

[24058263 rows x 2 columns]

In [ ]:
# Checking all the movie id's present in our data
movie_count = df[df['CustID'].str.contains(':')].count()[0]

<ipython-input-4-9f79fe6c1704>:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  movie_count = df[df['CustID'].str.contains(':')].count()[0]

In [ ]:
movie_count

4499

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24058263 entries, 0 to 24058262
Data columns (total 2 columns):
 #   Column   Dtype
---  ------   -----
 0   CustID   object
 1   Ratings  float64
dtypes: float64(1), object(1)
memory usage: 367.1+ MB

In [ ]:
# Number of unique customer id in our data.
cust_count = df['CustID'].nunique()

In [ ]:
cust_count
# In this total customer id count the movid id will be also counted.
cust_count = cust_count-movie_count
cust_count

470758

In [ ]:
# Segregation of our data
# For every row in CustID we will run a loop and select the row where we have colon and then store it in y after replacing colon with nothing "".

In [ ]:
movie_np = []
for x in df['CustID']:
    if ':' in x:
        y = x.replace(':',"")
    movie_np.append(y)

In [ ]:
movie_np

['1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 ...]

In [ ]:
df['MovieID'] = movie_np
df

           CustID  Ratings MovieID
0              1:      NaN       1
1         1488844      3.0       1
2          822109      5.0       1
3          885013      4.0       1
4           30878      4.0       1
...           ...      ...     ...
24058258  2591364      2.0    4499
24058259  1791000      2.0    4499
24058260   512536      5.0    4499
24058261   988963      3.0    4499
24058262  1704416      3.0    4499

[24058263 rows x 3 columns]

In [ ]:
df.isnull().sum()

CustID        0
Ratings    4499
MovieID       0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

CustID     0
Ratings    0
MovieID    0
dtype: int64

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   CustID   object
 1   Ratings  float64
 2   MovieID  object
dtypes: float64(1), object(2)
memory usage: 734.1+ MB

In [ ]:
# convertinf CustID, MovieID columns datatype to int

df['CustID'] = df['CustID'].astype(int)
df['MovieID'] = df['MovieID'].astype(int)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   CustID   int64
 1   Ratings  float64
 2   MovieID  int64
dtypes: float64(1), int64(2)
memory usage: 734.1 MB

In [ ]:
# Manual Filteration
# Nneed to get the count of every customer with respect to rating.
data_cust_summary = df.groupby('CustID')['Ratings'].count()
data_cust_summary

CustID
6          153
7          195
8           21
10          49
25           4
          ...
2649404     12
2649409     10
2649421      3
2649426     74
2649429     62
Name: Ratings, Length: 470758, dtype: int64

In [ ]:
cust_benchmark = round(data_cust_summary.quantile(0.60))
# I will select only those customers who have seen more than 36 movies.
cust_benchmark

36

In [ ]:
Rejected_cust = data_cust_summary[data_cust_summary<cust_benchmark].index
# When we use groupby fxn the column becomes index
Rejected_cust

Index([      8,      25,      33,      83,      94,     126,     130,     133,
           142,     149,
       ...
       2649337, 2649343, 2649351, 2649376, 2649379, 2649384, 2649401, 2649404,
       2649409, 2649421],
      dtype='int64', name='CustID', length=282042)

In [ ]:
# Filtering our movie data
# First we will get the count of ratings for every movie.
data_movie_summary = df.groupby('MovieID')['Ratings'].count()
data_movie_summary

MovieID
1        547
2        145
3       2012
4        142
5       1140
        ...
4495     614
4496    9519
4497     714
4498     269
4499     428
Name: Ratings, Length: 4499, dtype: int64

In [ ]:
movie_benchmark = round(data_movie_summary.quantile(0.60))
movie_benchmark

908

In [ ]:
Rejected_movies = data_movie_summary[data_movie_summary<movie_benchmark].index
Rejected_movies

Index([   1,    2,    4,    7,    9,   10,   11,   12,   13,   14,
       ...
       4480, 4481, 4486, 4487, 4491, 4494, 4495, 4497, 4498, 4499],
      dtype='int64', name='MovieID', length=2699)

In [ ]:
# Now we have selected the customers and movies that we need to reject.
# Now we will update the result in our actual dataframe (removing these rejected values)

In [ ]:
df[df['MovieID'].isin(Rejected_movies)]  # Here are all the movies that we need to reject

           CustID  Ratings  MovieID
1         1488844      3.0        1
2          822109      5.0        1
3          885013      4.0        1
4           30878      4.0        1
5          823519      3.0        1
...           ...      ...      ...
24058258  2591364      2.0     4499
24058259  1791000      2.0     4499
24058260   512536      5.0     4499
24058261   988963      3.0     4499
24058262  1704416      3.0     4499

[835479 rows x 3 columns]

In [ ]:
df = df[~df['MovieID'].isin(Rejected_movies)]
df

           CustID  Ratings  MovieID
695       1025579      4.0        3
696        712664      5.0        3
697       1331154      4.0        3
698       2632461      3.0        3
699         44937      5.0        3
...           ...      ...      ...
24056844   267802      4.0     4496
24056845  1559566      3.0     4496
24056846   293198      3.0     4496
24056847    70814      2.0     4496
24056848  1316220      5.0     4496

[23218285 rows x 3 columns]

In [ ]:
df = df[~df['CustID'].isin(Rejected_cust)]
df

           CustID  Ratings  MovieID
696        712664      5.0        3
697       1331154      4.0        3
698       2632461      3.0        3
699         44937      5.0        3
700        656399      4.0        3
...           ...      ...      ...
24056842  1055714      5.0     4496
24056843  2643029      4.0     4496
24056844   267802      4.0     4496
24056845  1559566      3.0     4496
24056846   293198      3.0     4496

[19695836 rows x 3 columns]

In [ ]:
df_title =pd.read_csv("/content/NetflixMovieData.csv", header=None,usecols=[0,1,2],names=['MovieID','Year','Name'])

df_title

       MovieID    Year                                               Name
0            1  2003.0                                    Dinosaur Planet
1            2  2004.0                         Isle of Man TT 2004 Review
2            3  1997.0                                          Character
3            4  1994.0                       Paula Abdul's Get Up & Dance
4            5  2004.0                           The Rise and Fall of ECW
...        ...     ...                                                ...
17764    17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17765    17767  2004.0                  Fidel Castro: American Experience
17766    17768  2000.0                                              Epoch
17767    17769  2003.0                                        The Company
17768    17770  2003.0                                       Alien Hunter

[17769 rows x 3 columns]

In [ ]:
 ! pip install Scikit-surprise

Requirement already satisfied: Scikit-surprise in /usr/local/lib/python3.11/dist-packages (1.1.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from Scikit-surprise) (1.4.2)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from Scikit-surprise) (1.23.5)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from Scikit-surprise) (1.15.2)

In [ ]:
! pip uninstall numpy

Found existing installation: numpy 1.23.5
Uninstalling numpy-1.23.5:
  Would remove:
    /usr/local/bin/f2py
    /usr/local/bin/f2py3
    /usr/local/bin/f2py3.11
    /usr/local/lib/python3.11/dist-packages/numpy-1.23.5.dist-info/*
    /usr/local/lib/python3.11/dist-packages/numpy.libs/libgfortran-040039e1.so.5.0.0
    /usr/local/lib/python3.11/dist-packages/numpy.libs/libopenblas64_p-r0-742d56dc.3.20.so
    /usr/local/lib/python3.11/dist-packages/numpy.libs/libquadmath-96973f99.so.0.0.0
    /usr/local/lib/python3.11/dist-packages/numpy/*
Proceed (Y/n)? y
  Successfully uninstalled numpy-1.23.5

In [ ]:
!pip install numpy==1.23.5

Collecting numpy==1.23.5
  Using cached numpy-1.23.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.3 kB)
Using cached numpy-1.23.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imbalanced-learn 0.13.0 requires numpy<3,>=1.24.3, but you have numpy 1.23.5 which is incompatible.
albucore 0.0.24 requires numpy>=1.24.4, but you have numpy 1.23.5 which is incompatible.
xarray 2025.3.1 requires numpy>=1.24, but you have numpy 1.23.5 which is incompatible.
jaxlib 0.5.1 requires numpy>=1.25, but you have numpy 1.23.5 which is incompatible.
scikit-image 0.25.2 requires numpy>=1.24, but you have numpy 1.23.5 which is incompatible.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 1.23.5 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.23.5 which is incompatible.
blosc2 3.3.2 requires numpy>=1.26, but you have numpy 1.23.5 which is incompatible.
treescope 0.1.9 requires numpy>=1.25.2, but you have numpy 1.23.5 which is incompatible.
pymc 5.22.0 requires numpy>=1.25.0, but you have numpy 1.23.5 which is incompatible.
albumentations 2.0.6 requires numpy>=1.24.4, but you have numpy 1.23.5 which is incompatible.
jax 0.5.2 requires numpy>=1.25, but you have numpy 1.23.5 which is incompatible.
bigframes 2.1.0 requires numpy>=1.24.0, but you have numpy 1.23.5 which is incompatible.
chex 0.1.89 requires numpy>=1.24.1, but you have numpy 1.23.5 which is incompatible.
Successfully installed numpy-1.23.5

In [ ]:
from surprise import Reader, Dataset, SVD
from surprise.model_selection import cross_validate

In [ ]:
reader = Reader()

In [ ]:
df

           CustID  Ratings  MovieID
696        712664      5.0        3
697       1331154      4.0        3
698       2632461      3.0        3
699         44937      5.0        3
700        656399      4.0        3
...           ...      ...      ...
24056842  1055714      5.0     4496
24056843  2643029      4.0     4496
24056844   267802      4.0     4496
24056845  1559566      3.0     4496
24056846   293198      3.0     4496

[19695836 rows x 3 columns]

In [ ]:
data = Dataset.load_from_df(df[['CustID','MovieID','Ratings']][:1000000],reader)

In [ ]:
model = SVD()

In [ ]:
cross_validate(model,data,measures=['RMSE'],cv=3)

{'test_rmse': array([0.9672161 , 0.96852838, 0.9699821 ]),
 'fit_time': (14.674408435821533, 15.224591970443726, 15.28437352180481),
 'test_time': (3.765780448913574, 3.2859909534454346, 3.899442195892334)}

**Recommendation**

Recommendation for any particular user for all those movie which are not rated by him.

In [ ]:
df.head()

      CustID  Ratings  MovieID
696   712664      5.0        3
697  1331154      4.0        3
698  2632461      3.0        3
699    44937      5.0        3
700   656399      4.0        3

In [ ]:
df_title.head()

   MovieID    Year                          Name
0        1  2003.0               Dinosaur Planet
1        2  2004.0    Isle of Man TT 2004 Review
2        3  1997.0                     Character
3        4  1994.0  Paula Abdul's Get Up & Dance
4        5  2004.0      The Rise and Fall of ECW

In [ ]:
# Creating a copy of the df_title DataFrame for user 712664
user_712664 = df_title.copy()

# Check the copied DataFrame
print(user_712664.head())

   MovieID    Year                          Name
0        1  2003.0               Dinosaur Planet
1        2  2004.0    Isle of Man TT 2004 Review
2        3  1997.0                     Character
3        4  1994.0  Paula Abdul's Get Up & Dance
4        5  2004.0      The Rise and Fall of ECW

In [ ]:
# identifying the unrated movies of user id 712664

# Step 1: Define the user ID and identify rated movies
user_id = 712664

# Movies the user has already rated
rated_movies = df[df['CustID'] == user_id]['MovieID'].unique()

# Step 2: Find unrated movies (those that user hasn't rated yet)
unrated_movies = df_title[~df_title['MovieID'].isin(rated_movies)]

# Step 3: Predict ratings for each unrated movie
predictions = []
for movie_id in unrated_movies['MovieID']:
    pred = model.predict(user_id, movie_id)
    predictions.append((movie_id, pred.est))

# Step 4: Create a DataFrame from the predictions
pred_df = pd.DataFrame(predictions, columns=['MovieID', 'PredictedRating'])

# Step 5: Merge predictions with movie details (movie name and year)
user_712664 = df_title.merge(pred_df, on='MovieID')

# Step 6: Sort by predicted ratings and recommend top 10 movies
top_recommendations = user_712664.sort_values('PredictedRating', ascending=False).head(10)

# Step 7: Display the top recommended movies
print(top_recommendations[['Name', 'Year', 'PredictedRating']])

                                                  Name    Year  \
28   ABC Primetime: Mel Gibson's The Passion of the...  2004.0
64                                         Invader Zim  2004.0
250                         Sex and the City: Season 4  2001.0
156                                         The Chorus  2004.0
235                               A Night at the Opera  1935.0
72                               I Love Lucy: Season 2  1952.0
224     Neon Genesis Evangelion: The End of Evangelion  1995.0
223                                  Woman of the Year  1942.0
206                         Chappelle's Show: Season 1  2003.0
128                       Star Trek: Voyager: Season 1  1995.0

     PredictedRating
28          4.951955
64          4.779745
250         4.733654
156         4.717833
235         4.625659
72          4.571071
224         4.566005
223         4.473265
206         4.406466
128         4.400337

In [ ]:
# recommendation for any particular user for all those movie.

user_1488844 = df_title.copy()

In [ ]:
user_1488844['Estimate Score'] = user_1488844['MovieID'].apply(lambda x : model.predict(1488844,x).est)

In [ ]:
user_1488844

,MovieID,Year,Name,Estimate Score
0,1,2003.0,Dinosaur Planet,3.291027
1,2,2004.0,Isle of Man TT 2004 Review,3.291027
2,3,1997.0,Character,3.229188
3,4,1994.0,Paula Abdul's Get Up & Dance,3.291027
4,5,2004.0,The Rise and Fall of ECW,3.933959
...,...,...,...,...
17764,17766,2002.0,Where the Wild Things Are and Other Maurice Se...,3.291027
17765,17767,2004.0,Fidel Castro: American Experience,3.291027
17766,17768,2000.0,Epoch,3.291027
17767,17769,2003.0,The Company,3.291027
17768,17770,2003.0,Alien Hunter,3.291027

In [ ]:
# The movies with highest rating will be recommended to the user.

user_1488844.sort_values('Estimate Score',ascending=False).head()

,MovieID,Year,Name,Estimate Score
269,270,2001.0,Sex and the City: Season 4,4.325811
252,253,1935.0,A Night at the Opera,4.088487
105,106,2004.0,Stevie Ray Vaughan and Double Trouble: Live at...,3.949137
4,5,2004.0,The Rise and Fall of ECW,3.933959
240,241,1959.0,North by Northwest,3.924872